#Initializing version properties file at location : /Users/khalilperso/Documents/projects/n/open-source/semantic-version/example/version.properties
#Sun Feb 01 12:47:43 CET 2026
patch=0
major=0
minor=0
